### ISSUE TITLE
redis pool blocked when plugin is used in tests

### ISSUE THREAD

**Issue by cevantes** [typesafehub/play-plugins#73]
I wrote tests for my authorization controller and every time I run more than one test concurrently there is a 
JedisConnectionException: Could not get a resource from the pool (Pool.java:22)
[error] redis.clients.util.Pool.getResource(Pool.java:22)
[error] org.sedis.Pool.withClient(sedis.scala:71)
...
[error] Pool not open

**Comment by peter-fu** [comment]
+1

This happens because when running multiple tests the lifecycle stopHook is executed and the jedisPool is then destroyed when the first test ends, however, the JedisPoolProvider still holds the destroyed jedisPool and returns it for the next test.

https://github.com/typesafehub/play-plugins/blob/c4dcf3d6b0948b3211372efd836568eab5844b32/redis/src/main/scala/com/typesafe/play/redis/JedisPoolProvider.scala#L49
